/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as DevicesIndexRouteImport } from './routes/devices.index'
import { Route as DevicesDeviceIdRouteImport } from './routes/devices.$deviceId'
import { Route as ApiAgentHealthRouteImport } from './routes/api/agent.health'
import { Route as ApiAgentReportRouteImport } from './routes/api/agent.report'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesIndexRoute = DevicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevicesRoute,
} as any)
const DevicesDeviceIdRoute = DevicesDeviceIdRouteImport.update({
  id: '/$deviceId',
  path: '/$deviceId',
  getParentRoute: () => DevicesRoute,
} as any)
const ApiAgentHealthRoute = ApiAgentHealthRouteImport.update({
  id: '/api/agent/health',
  path: '/api/agent/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentReportRoute = ApiAgentReportRouteImport.update({
  id: '/api/agent/report',
  path: '/api/agent/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/alerts': typeof AlertsRoute
  '/devices': typeof DevicesRouteWithChildren
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRoute
  '/devices/': typeof DevicesIndexRoute
  '/api/agent/health': typeof ApiAgentHealthRoute
  '/api/agent/report': typeof ApiAgentReportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/alerts': typeof AlertsRoute
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRoute
  '/devices': typeof DevicesIndexRoute
  '/api/agent/health': typeof ApiAgentHealthRoute
  '/api/agent/report': typeof ApiAgentReportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/alerts': typeof AlertsRoute
  '/devices': typeof DevicesRouteWithChildren
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRoute
  '/devices/': typeof DevicesIndexRoute
  '/api/agent/health': typeof ApiAgentHealthRoute
  '/api/agent/report': typeof ApiAgentReportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/alerts'
    | '/devices'
    | '/login'
    | '/policies'
    | '/devices/$deviceId'
    | '/devices/'
    | '/api/agent/health'
    | '/api/agent/report'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/alerts'
    | '/login'
    | '/policies'
    | '/devices/$deviceId'
    | '/devices'
    | '/api/agent/health'
    | '/api/agent/report'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/alerts'
    | '/devices'
    | '/login'
    | '/policies'
    | '/devices/$deviceId'
    | '/devices/'
    | '/api/agent/health'
    | '/api/agent/report'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  AlertsRoute: typeof AlertsRoute
  DevicesRoute: typeof DevicesRouteWithChildren
  LoginRoute: typeof LoginRoute
  PoliciesRoute: typeof PoliciesRoute
  ApiAgentHealthRoute: typeof ApiAgentHealthRoute
  ApiAgentReportRoute: typeof ApiAgentReportRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/': {
      id: '/devices/'
      path: '/'
      fullPath: '/devices/'
      preLoaderRoute: typeof DevicesIndexRouteImport
      parentRoute: typeof DevicesRoute
    }
    '/devices/$deviceId': {
      id: '/devices/$deviceId'
      path: '/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof DevicesDeviceIdRouteImport
      parentRoute: typeof DevicesRoute
    }
    '/api/agent/health': {
      id: '/api/agent/health'
      path: '/api/agent/health'
      fullPath: '/api/agent/health'
      preLoaderRoute: typeof ApiAgentHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/report': {
      id: '/api/agent/report'
      path: '/api/agent/report'
      fullPath: '/api/agent/report'
      preLoaderRoute: typeof ApiAgentReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DevicesRouteChildren {
  DevicesDeviceIdRoute: typeof DevicesDeviceIdRoute
  DevicesIndexRoute: typeof DevicesIndexRoute
}

const DevicesRouteChildren: DevicesRouteChildren = {
  DevicesDeviceIdRoute: DevicesDeviceIdRoute,
  DevicesIndexRoute: DevicesIndexRoute,
}

const DevicesRouteWithChildren =
  DevicesRoute._addFileChildren(DevicesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  AlertsRoute: AlertsRoute,
  DevicesRoute: DevicesRouteWithChildren,
  LoginRoute: LoginRoute,
  PoliciesRoute: PoliciesRoute,
  ApiAgentHealthRoute: ApiAgentHealthRoute,
  ApiAgentReportRoute: ApiAgentReportRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
